name: Release New Action Version
on:
  push:
    branches:
      - "main"

jobs:
  release-action:
    name: Release new version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump Version
        uses: patriotsoftware/semver-bump-action@v1
